-- Create the PRODUCT table if it does not exist
CREATE TABLE IF NOT EXISTS PRODUCTS(
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
    );

    INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
    ('1', 'Sajid CHAIS', '1','1','10 BOXES*20 BAGS',18),
    ('2', 'Sajid CHANG', '1','1','24-12 OZ BOTTLES',19),
    ('3', 'Safwan SYRUP', '1','2','12-550 ML BOTTLES',10),
    ('4', 'CHEF AFNAN SEASONING', '2','2','48- 6 OZ JARS',22),
    ('5', 'CHEF AFNAN MIX', '2','2','36 BOXES',21.35);

    SELECT COUNT(PRODUCT_ID) AS Product_Count FROM PRODUCTS;

    SELECT AVG(PRICE) AS Average_Price FROM PRODUCTS;

    SELECT SUM(PRICE) AS Total_Price FROM PRODUCTS;